# Generated by Django 6.0.4 on 2026-05-06 00:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('surveys', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='feedback',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='surveys.instructor'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['course'], name='surveys_fee_course__a651b5_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['instructor'], name='surveys_fee_instruc_7bf389_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['semester'], name='surveys_fee_semeste_c62a9c_idx'),
        ),
        migrations.AddIndex(
            model_name='feedback',
            index=models.Index(fields=['feedback_type'], name='surveys_fee_feedbac_5f12df_idx'),
        ),
    ]
