# Generated by Django 6.0.4 on 2026-05-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructor',
            name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='instructors',
            field=models.ManyToManyField(blank=True, related_name='courses', to='surveys.instructor'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='instructor',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
