# Generated by Django 6.0.4 on 2026-06-01 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('surveys', '0003_remove_instructor_name_course_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='semester',
            field=models.CharField(choices=[('T1', 'Term 1'), ('T2', 'Term 2'), ('T3', 'Term 3')], max_length=10),
        ),
    ]
